name: DevSecOps Pipelines
on:
  push:
    branches:
      - devsecops-pipelines

jobs:
#SAST
  sast:
    name: SAST
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: build dependencies
        run: npm install

      - name: SonarCloud scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=somme
            -Dsonar.projectKey=${{ github.event.repository.name }}
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
            -Dsonar.qualitygate.wait=true
            