name: DevSecOps Pipelines
on:
  push:
    branches: [ main, devsecops-pipelines ]
  pull_request:
    branches: [ main, devsecops-pipelines ]

jobs:
#ENTORNO
  BUILD:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.17.0'
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: build dependencies
        run: npm install
      - name: compilacion
        run: |
          npm run build
      - name: Upload build output
        uses: actions/upload-artifact@master
        with:
          name: build-artifact
          path: ${{ github.workspace }}/.next
          include-hidden-files: true


#SAST

  SAST:
    needs: BUILD
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download build artifact
        uses: actions/download-artifact@master
        with:
          name: build-artifact
          path: ${{ github.workspace }}/.next
          include-hidden-files: true
      - name: Validando existencia del proyecto en sonar
        run: |
          set +e
          curl -f -X POST -u '${{ secrets.SONAR_TOKEN }}:' 'https://sonarcloud.io/api/projects/create' -d 'name=SommeIKC_laboratorio-final' -d 'project=SommeIKC_laboratorio-final' -d 'organization=somme' -d 'visibility=public'
          if [ $? -ne 0 ]; then
            echo "Proyecto ya existe en Sonarcloud"
            echo "::set-output name=proyectoExiste::1"
          else
            echo "Proyecto SommeIKC_laboratorio-final creado exitosamente en Sonarcloud"
          
            echo "Se establece rama main como rama por defecto"
            curl -X POST -u "${{ secrets.SONAR_TOKEN }}:" 'https://sonarcloud.io/api/project_branches/rename' -d 'name=main' -d 'project=laboratorio-final'
          fi
          set -e    
      - name: SonarCloud scan
        run: |
          npx sonarqube-scanner \
            -Dsonar.projectKey=SommeIKC_laboratorio-final \
            -Dsonar.organization=somme \
            -Dsonar.sources=. \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
            -Dsonar.branch.name=main

      - name: Validar resultado de SonarCloud (SAST)
        run: |
          project_key="SommeIKC_laboratorio-final"
          branchName="main"
      
          issueCount=$(curl -s -u "${{ secrets.SONAR_TOKEN }}:" \
            "https://sonarcloud.io/api/issues/search?componentKeys=${projectKey}&branch=${branchName}&types=VULNERABILITY&severities=BLOCKER,CRITICAL,MAJOR" \
            | jq '.total')

          echo "Vulnerabilidades críticas/altas/medias encontradas: $issueCount"

          if [ "$issueCount" -gt 0 ]; then
            echo "Se encontraron vulnerabilidades críticas, altas o medias. Deteniendo el pipeline..."
            exit 1
          else
            echo "No se encontraron vulnerabilidades críticas, altas ni medias. Continuando..."
          fi
  SCA:
    needs: SAST
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install Dependency-Check
      run: |
          curl -L -o dc.zip https://github.com/jeremylong/DependencyCheck/releases/download/v8.4.0/dependency-check-8.4.0-release.zip
          unzip dc.zip -d dc
          chmod +x dc/dependency-check/bin/dependency-check.sh

    - name: Run OWASP Dependency-Check
      run: |
          ./dc/dependency-check/bin/dependency-check.sh \
            --project "laboratorio-final" \
            --scan . \
            --format "JSON" \
            --out dependency-check-report

    - name: Validar resultado del SCA
      run: |
          crits=$(jq '[.dependencies[].vulnerabilities[]? | select(.severity == "Critical" or .severity == "High" or .severity == "Medium")] | length' dependency-check-report/dependency-check-report.json)
          echo "Vulnerabilidades críticas/altas/medias encontradas: $crits"
          if [ "$crits" -gt 0 ]; then
            echo "Fallo en análisis SCA por vulnerabilidades"
            exit 1
          fi

    - name: Guardar reporte de SCA como artefacto
      uses: actions/upload-artifact@v3
      with:
        name: reporte-sca
        path: ${{github.workspace}}/dependency-check-report

#DAST


